import { TradeJournalEntry, OpenPosition } from '../types';

/**
 * Generates a relative date string (YYYY-MM-DD) offset by `daysAgo` days from today.
 */
function getDateString(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
}

/**
 * Returns a comprehensive, realistic set of 16 closed crypto perpetual futures trades
 * spanning the last 14 days up to today.
 */
export function getSampleTrades(): Omit<TradeJournalEntry, 'id'>[] {
  const now = new Date();

  return [
    // 1. TODAY - BTC Long Win
    {
      createdAt: new Date(now.getTime() - 2 * 3600 * 1000).toISOString(),
      date: getDateString(0),
      time: '11:30',
      pair: 'BTCUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 62450,
      exitPrice: 63800,
      stopLoss: 61850,
      takeProfit: 64200,
      positionSize: 5000,
      quantity: 5000 / 62450,
      margin: 500,
      tradingFee: 0.055,
      grossPnl: 108.09,
      pnl: 102.59,
      pnlPercentage: 20.52,
      rMultiple: 2.25,
      riskAmount: 48.04,
      riskPercentage: 1.0,
      strategy: 'Breakout',
      setup: '4H Range Breakout',
      timeframe: '4h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Confident',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['Breakout', 'HighConfidence', 'CleanExecution'],
      entryReason: 'Clean 4H close above weekly consolidation resistance with rising volume.',
      exitReason: 'Scaled out into major order block resistance as planned.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Patience in letting the 4H candle confirm prevented getting faked out.',
      notes: 'Executed with strict adherence to 1% risk rule.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 2. TODAY - SOL Short Loss
    {
      createdAt: new Date(now.getTime() - 5 * 3600 * 1000).toISOString(),
      date: getDateString(0),
      time: '08:45',
      pair: 'SOLUSDT',
      exchange: 'Bybit',
      direction: 'SHORT',
      leverage: 10,
      entryPrice: 147.20,
      exitPrice: 149.80,
      stopLoss: 149.80,
      takeProfit: 142.00,
      positionSize: 2500,
      quantity: 2500 / 147.20,
      margin: 250,
      tradingFee: 0.055,
      grossPnl: -44.16,
      pnl: -46.91,
      pnlPercentage: -18.76,
      rMultiple: -1.0,
      riskAmount: 44.16,
      riskPercentage: 1.0,
      strategy: 'Reversal',
      setup: 'Double Top Retest',
      timeframe: '15m',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Anxious',
      emotionAfter: 'Calm',
      tradeRating: 3,
      tags: ['Reversal', 'StoppedOut'],
      entryReason: 'Expected rejection off $147.50 resistance after 15m bearish engulfing.',
      exitReason: 'Hit stop loss cleanly when buyers absorbed resistance.',
      mistakesMade: 'Counter-trend entry during high volume session.',
      mistakes: ['No clear setup'],
      lessonsLearned: 'Do not short high beta assets when BTC is grinding up aggressively.',
      notes: 'Controlled stop loss protected capital.',
      isWin: false,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 3. YESTERDAY - ETH Long Win
    {
      createdAt: new Date(now.getTime() - 26 * 3600 * 1000).toISOString(),
      date: getDateString(1),
      time: '14:20',
      pair: 'ETHUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 2480,
      exitPrice: 2565,
      stopLoss: 2445,
      takeProfit: 2580,
      positionSize: 4000,
      quantity: 4000 / 2480,
      margin: 400,
      tradingFee: 0.055,
      grossPnl: 137.10,
      pnl: 132.70,
      pnlPercentage: 33.18,
      rMultiple: 2.43,
      riskAmount: 56.45,
      riskPercentage: 1.2,
      strategy: 'Trend Following',
      setup: '1H EMA 20 Bounce',
      timeframe: '1h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['TrendFollowing', 'HighConfidence', 'CleanExecution'],
      entryReason: 'Retest of previous session high turning into support with 1H bullish pin bar.',
      exitReason: 'Target 1 hit at $2,565.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Trading with the higher timeframe trend provides higher probability.',
      notes: 'Super smooth continuation trade.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 4. YESTERDAY - SUI Long Win
    {
      createdAt: new Date(now.getTime() - 30 * 3600 * 1000).toISOString(),
      date: getDateString(1),
      time: '10:15',
      pair: 'SUIUSDT',
      exchange: 'OKX',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 2.15,
      exitPrice: 2.38,
      stopLoss: 2.07,
      takeProfit: 2.42,
      positionSize: 2000,
      quantity: 2000 / 2.15,
      margin: 200,
      tradingFee: 0.06,
      grossPnl: 213.95,
      pnl: 211.55,
      pnlPercentage: 105.78,
      rMultiple: 2.87,
      riskAmount: 74.42,
      riskPercentage: 1.5,
      strategy: 'Momentum',
      setup: 'Volume Breakout',
      timeframe: '15m',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Confident',
      emotionAfter: 'Confident',
      tradeRating: 5,
      tags: ['Momentum', 'Runner', 'Breakout'],
      entryReason: 'Massive surge in spot CVD and open interest breaking multi-day resistance.',
      exitReason: 'Trailing stop triggered after 10% move.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Letting winners run when momentum is strong significantly boosts expectancy.',
      notes: 'Outstanding runner trade.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 5. 2 DAYS AGO - DOGE Short Win
    {
      createdAt: new Date(now.getTime() - 50 * 3600 * 1000).toISOString(),
      date: getDateString(2),
      time: '16:00',
      pair: 'DOGEUSDT',
      exchange: 'Binance',
      direction: 'SHORT',
      leverage: 10,
      entryPrice: 0.1380,
      exitPrice: 0.1290,
      stopLoss: 0.1420,
      takeProfit: 0.1280,
      positionSize: 2000,
      quantity: 2000 / 0.1380,
      margin: 200,
      tradingFee: 0.055,
      grossPnl: 130.43,
      pnl: 128.23,
      pnlPercentage: 64.12,
      rMultiple: 2.25,
      riskAmount: 57.97,
      riskPercentage: 1.1,
      strategy: 'Mean Reversion',
      setup: 'Blow-off Top Exhaustion',
      timeframe: '1h',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      tradeRating: 4,
      tags: ['MeanReversion', 'CleanExecution'],
      entryReason: 'Bearish divergence on 1H RSI following parabolic pump.',
      exitReason: 'Closed near daily VWAP support.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Waiting for the first lower high confirmed the top.',
      notes: 'Clean mean reversion setup.',
      isWin: true,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 6. 3 DAYS AGO - BTC Short Loss
    {
      createdAt: new Date(now.getTime() - 74 * 3600 * 1000).toISOString(),
      date: getDateString(3),
      time: '19:30',
      pair: 'BTCUSDT',
      exchange: 'Binance',
      direction: 'SHORT',
      leverage: 10,
      entryPrice: 63200,
      exitPrice: 63950,
      stopLoss: 63950,
      takeProfit: 61800,
      positionSize: 4500,
      quantity: 4500 / 63200,
      margin: 450,
      tradingFee: 0.055,
      grossPnl: -53.40,
      pnl: -58.35,
      pnlPercentage: -12.97,
      rMultiple: -1.0,
      riskAmount: 53.40,
      riskPercentage: 1.0,
      strategy: 'Reversal',
      setup: 'Range High Fakeout',
      timeframe: '1h',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Excited',
      emotionAfter: 'Calm',
      tradeRating: 3,
      tags: ['NewsVolatility', 'StoppedOut'],
      entryReason: 'Attempted to short range high test.',
      exitReason: 'Unexpected ETF flow news sparked a sudden push past stop loss.',
      mistakesMade: 'Traded right before US market close without checking news feeds.',
      mistakes: ['Emotional decision'],
      lessonsLearned: 'Avoid counter-trend shorts leading into high volatility news hours.',
      notes: 'Stop loss kept damage under 1.2%.',
      isWin: false,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 7. 4 DAYS AGO - SOL Long Win
    {
      createdAt: new Date(now.getTime() - 98 * 3600 * 1000).toISOString(),
      date: getDateString(4),
      time: '12:00',
      pair: 'SOLUSDT',
      exchange: 'Bybit',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 141.50,
      exitPrice: 147.80,
      stopLoss: 139.00,
      takeProfit: 148.00,
      positionSize: 3000,
      quantity: 3000 / 141.50,
      margin: 300,
      tradingFee: 0.055,
      grossPnl: 133.57,
      pnl: 130.27,
      pnlPercentage: 43.42,
      rMultiple: 2.52,
      riskAmount: 53.00,
      riskPercentage: 1.0,
      strategy: 'Breakout',
      setup: 'Bull Flag Continuation',
      timeframe: '4h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Calm',
      emotionAfter: 'Confident',
      tradeRating: 5,
      tags: ['Breakout', 'HighConfidence', 'Discipline'],
      entryReason: '4H bull flag breakout aligned with higher timeframe trend.',
      exitReason: 'Hit take profit precisely at resistance.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Higher timeframe setups have much higher follow-through.',
      notes: 'Executed cleanly.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 8. 5 DAYS AGO - ETH Short Loss (FOMO mistake)
    {
      createdAt: new Date(now.getTime() - 122 * 3600 * 1000).toISOString(),
      date: getDateString(5),
      time: '15:10',
      pair: 'ETHUSDT',
      exchange: 'Binance',
      direction: 'SHORT',
      leverage: 15,
      entryPrice: 2420,
      exitPrice: 2465,
      stopLoss: 2465,
      takeProfit: 2350,
      positionSize: 3500,
      quantity: 3500 / 2420,
      margin: 233.33,
      tradingFee: 0.055,
      grossPnl: -65.08,
      pnl: -68.93,
      pnlPercentage: -29.54,
      rMultiple: -1.0,
      riskAmount: 65.08,
      riskPercentage: 1.3,
      strategy: 'Breakdown',
      setup: 'Support Breakdown',
      timeframe: '5m',
      confidence: 'Low',
      setupQuality: 'Poor',
      emotionBefore: 'Anxious',
      emotionAfter: 'Frustrated',
      tradeRating: 2,
      tags: ['FOMO', 'EnteredLate', 'Emotional'],
      entryReason: 'Saw price dumping and chased the red candle without waiting for a retest.',
      exitReason: 'Wicked out on instant V-shape bounce.',
      mistakesMade: 'FOMO chased a red candle on 5m chart; entered late without a setup.',
      mistakes: ['FOMO', 'Entered late'],
      lessonsLearned: 'Never market-order short at the bottom of a fast dump. Wait for the retest.',
      notes: 'Classic FOMO mistake. Recorded in mistake journal.',
      isWin: false,
      isBreakeven: false,
      favorite: false,
      planCompliance: false,
    },

    // 9. 6 DAYS AGO - BTC Long Win (Order Block Sweep)
    {
      createdAt: new Date(now.getTime() - 146 * 3600 * 1000).toISOString(),
      date: getDateString(6),
      time: '09:00',
      pair: 'BTCUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 60800,
      exitPrice: 62550,
      stopLoss: 60150,
      takeProfit: 62600,
      positionSize: 5000,
      quantity: 5000 / 60800,
      margin: 500,
      tradingFee: 0.055,
      grossPnl: 143.91,
      pnl: 138.41,
      pnlPercentage: 27.68,
      rMultiple: 2.69,
      riskAmount: 53.45,
      riskPercentage: 1.0,
      strategy: 'Order Block',
      setup: 'Liquidity Sweep & Reclaim',
      timeframe: '1h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Confident',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['OrderBlock', 'HighConfidence', 'CleanExecution'],
      entryReason: 'Clean sweep of Monday low followed by aggressive absorption & 1H close back in range.',
      exitReason: 'Hit take profit target near range high.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Liquidity sweeps followed by range reclaim are among the highest R:R trades.',
      notes: 'Textbook execution.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 10. 7 DAYS AGO - SUI Long Win
    {
      createdAt: new Date(now.getTime() - 170 * 3600 * 1000).toISOString(),
      date: getDateString(7),
      time: '13:45',
      pair: 'SUIUSDT',
      exchange: 'OKX',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 1.92,
      exitPrice: 2.11,
      stopLoss: 1.85,
      takeProfit: 2.12,
      positionSize: 2000,
      quantity: 2000 / 1.92,
      margin: 200,
      tradingFee: 0.06,
      grossPnl: 197.92,
      pnl: 195.52,
      pnlPercentage: 97.76,
      rMultiple: 2.71,
      riskAmount: 72.92,
      riskPercentage: 1.4,
      strategy: 'Trend Following',
      setup: 'Pullback to 4H EMA',
      timeframe: '4h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['TrendFollowing', 'HighConfidence'],
      entryReason: 'Healthy pullback to dynamic support in strong macro uptrend.',
      exitReason: 'TP reached near previous cycle high.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Trading top relative strength coins yields bigger moves than lagging alts.',
      notes: 'Great risk-to-reward ratio.',
      isWin: true,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 11. 8 DAYS AGO - SOL Short Win
    {
      createdAt: new Date(now.getTime() - 194 * 3600 * 1000).toISOString(),
      date: getDateString(8),
      time: '17:20',
      pair: 'SOLUSDT',
      exchange: 'Bybit',
      direction: 'SHORT',
      leverage: 10,
      entryPrice: 152.00,
      exitPrice: 146.50,
      stopLoss: 154.50,
      takeProfit: 146.00,
      positionSize: 3000,
      quantity: 3000 / 152.00,
      margin: 300,
      tradingFee: 0.055,
      grossPnl: 108.55,
      pnl: 105.25,
      pnlPercentage: 35.08,
      rMultiple: 2.20,
      riskAmount: 49.34,
      riskPercentage: 1.0,
      strategy: 'Reversal',
      setup: 'Bearish Divergence',
      timeframe: '1h',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Calm',
      emotionAfter: 'Relieved',
      tradeRating: 4,
      tags: ['Divergence', 'Technical'],
      entryReason: 'Triple bearish divergence on 1H RSI at major psychological $152 resistance.',
      exitReason: 'Closed out as price reached 4H support.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'RSI divergence works best when aligned with horizontal key levels.',
      notes: 'Clean execution.',
      isWin: true,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 12. 9 DAYS AGO - DOGE Long Loss
    {
      createdAt: new Date(now.getTime() - 218 * 3600 * 1000).toISOString(),
      date: getDateString(9),
      time: '11:15',
      pair: 'DOGEUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 0.1250,
      exitPrice: 0.1215,
      stopLoss: 0.1215,
      takeProfit: 0.1320,
      positionSize: 2000,
      quantity: 2000 / 0.1250,
      margin: 200,
      tradingFee: 0.055,
      grossPnl: -56.00,
      pnl: -58.20,
      pnlPercentage: -29.10,
      rMultiple: -1.0,
      riskAmount: 56.00,
      riskPercentage: 1.1,
      strategy: 'Breakout',
      setup: 'Ascending Triangle',
      timeframe: '15m',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Calm',
      emotionAfter: 'Calm',
      tradeRating: 3,
      tags: ['BreakoutFailure', 'StoppedOut'],
      entryReason: 'Ascending triangle breakout attempt.',
      exitReason: 'Breakout failed and rolled over; stop loss hit cleanly.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Breakout failures are normal; honor stop losses without hesitation.',
      notes: 'Acceptable loss within plan.',
      isWin: false,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    },

    // 13. 10 DAYS AGO - BTC Long Win
    {
      createdAt: new Date(now.getTime() - 242 * 3600 * 1000).toISOString(),
      date: getDateString(10),
      time: '07:30',
      pair: 'BTCUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 59500,
      exitPrice: 61100,
      stopLoss: 58850,
      takeProfit: 61200,
      positionSize: 5000,
      quantity: 5000 / 59500,
      margin: 500,
      tradingFee: 0.055,
      grossPnl: 134.45,
      pnl: 128.95,
      pnlPercentage: 25.79,
      rMultiple: 2.46,
      riskAmount: 54.62,
      riskPercentage: 1.0,
      strategy: 'Range Break',
      setup: 'London Open Expansion',
      timeframe: '15m',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Confident',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['SessionOpen', 'HighConfidence', 'CleanExecution'],
      entryReason: 'London session volume expansion reclaiming prior day value area high.',
      exitReason: 'Target hit during US morning session.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Trading session open momentum provides quick and clean expansions.',
      notes: 'Great follow-through.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 14. 11 DAYS AGO - ETH Long Loss (Moved Stop Loss mistake)
    {
      createdAt: new Date(now.getTime() - 266 * 3600 * 1000).toISOString(),
      date: getDateString(11),
      time: '14:00',
      pair: 'ETHUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 2530,
      exitPrice: 2470,
      stopLoss: 2490, // Planned SL was 2490, but moved to 2470
      takeProfit: 2620,
      positionSize: 3500,
      quantity: 3500 / 2530,
      margin: 350,
      tradingFee: 0.055,
      grossPnl: -83.00,
      pnl: -86.85,
      pnlPercentage: -24.81,
      rMultiple: -1.5,
      riskAmount: 55.34,
      riskPercentage: 1.1,
      strategy: 'Trend Following',
      setup: 'Support Bounce',
      timeframe: '1h',
      confidence: 'Medium',
      setupQuality: 'Good',
      emotionBefore: 'Anxious',
      emotionAfter: 'Regretful',
      tradeRating: 2,
      tags: ['MovedStopLoss', 'Emotional', 'DisciplineIssue'],
      entryReason: 'Support bounce attempt.',
      exitReason: 'Price broke support; panicked and moved stop-loss down $20, resulting in a larger loss.',
      mistakesMade: 'Moved stop loss down hoping for a bounce instead of accepting the planned stop.',
      mistakes: ['Moved stop-loss', 'Broke risk rules'],
      lessonsLearned: 'Never move stop losses away from entry. Accept the initial invalidation.',
      notes: 'Rule violation recorded in trade review.',
      isWin: false,
      isBreakeven: false,
      favorite: false,
      planCompliance: false,
    },

    // 15. 12 DAYS AGO - SOL Long Win
    {
      createdAt: new Date(now.getTime() - 290 * 3600 * 1000).toISOString(),
      date: getDateString(12),
      time: '10:30',
      pair: 'SOLUSDT',
      exchange: 'Bybit',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 135.00,
      exitPrice: 141.20,
      stopLoss: 132.50,
      takeProfit: 141.50,
      positionSize: 3000,
      quantity: 3000 / 135.00,
      margin: 300,
      tradingFee: 0.055,
      grossPnl: 137.78,
      pnl: 134.48,
      pnlPercentage: 44.83,
      rMultiple: 2.48,
      riskAmount: 55.56,
      riskPercentage: 1.1,
      strategy: 'Breakout',
      setup: 'Daily Level Reclaim',
      timeframe: '1d',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Confident',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['Breakout', 'HighConfidence', 'CleanExecution'],
      entryReason: 'Daily candle close reclaiming previous week high.',
      exitReason: 'Took profit ahead of key $142 overhead liquidity pool.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Daily level reclaims carry strong momentum.',
      notes: 'Clean execution according to plan.',
      isWin: true,
      isBreakeven: false,
      favorite: true,
      planCompliance: true,
    },

    // 16. 13 DAYS AGO - BTC Long Win
    {
      createdAt: new Date(now.getTime() - 314 * 3600 * 1000).toISOString(),
      date: getDateString(13),
      time: '08:00',
      pair: 'BTCUSDT',
      exchange: 'Binance',
      direction: 'LONG',
      leverage: 10,
      entryPrice: 58200,
      exitPrice: 59750,
      stopLoss: 57550,
      takeProfit: 59800,
      positionSize: 5000,
      quantity: 5000 / 58200,
      margin: 500,
      tradingFee: 0.055,
      grossPnl: 133.16,
      pnl: 127.66,
      pnlPercentage: 25.53,
      rMultiple: 2.38,
      riskAmount: 55.84,
      riskPercentage: 1.1,
      strategy: 'Trend Following',
      setup: 'Weekly Support Test',
      timeframe: '4h',
      confidence: 'High',
      setupQuality: 'Excellent',
      emotionBefore: 'Calm',
      emotionAfter: 'Satisfied',
      tradeRating: 5,
      tags: ['TrendFollowing', 'HighConfidence'],
      entryReason: 'Testing major macro ascending trendline on weekly timeframe.',
      exitReason: 'Closed before weekend consolidation.',
      mistakesMade: '',
      mistakes: [],
      lessonsLearned: 'Higher timeframe macro support zones offer asymmetric risk/reward.',
      notes: 'Great start to the trading period.',
      isWin: true,
      isBreakeven: false,
      favorite: false,
      planCompliance: true,
    }
  ];
}

/**
 * Returns 2 realistic active sample open positions to showcase the Portfolio and Risk Simulator tabs.
 */
export function getSampleOpenPositions(): Omit<OpenPosition, 'id'>[] {
  const now = new Date();

  return [
    {
      pair: 'BTCUSDT',
      direction: 'LONG',
      entryPrice: 62800,
      currentPrice: 63650,
      markPrice: 63640,
      stopLoss: 62100,
      takeProfit: 64800,
      quantity: 5000 / 62800,
      positionSize: 5000,
      margin: 500,
      leverage: 10,
      riskAmount: 55.73,
      unrealizedPnl: 67.68,
      unrealizedPnlPct: 13.54,
      liquidationPrice: 56834,
      distanceToLiquidationPct: 10.7,
      correlationGroup: 'BTC-Related',
      exchange: 'Binance',
      createdAt: new Date(now.getTime() - 4 * 3600 * 1000).toISOString(),
      notes: 'Active 4H continuation swing. Stop loss at breakeven after first resistance tag.',
    },
    {
      pair: 'SOLUSDT',
      direction: 'LONG',
      entryPrice: 145.20,
      currentPrice: 147.10,
      markPrice: 147.05,
      stopLoss: 142.80,
      takeProfit: 151.00,
      quantity: 2500 / 145.20,
      positionSize: 2500,
      margin: 250,
      leverage: 10,
      riskAmount: 41.32,
      unrealizedPnl: 32.71,
      unrealizedPnlPct: 13.08,
      liquidationPrice: 131.40,
      distanceToLiquidationPct: 10.6,
      correlationGroup: 'Layer-1s',
      exchange: 'Bybit',
      createdAt: new Date(now.getTime() - 2 * 3600 * 1000).toISOString(),
      notes: 'Holding through retest of 15m breakout level.',
    }
  ];
}
